# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0002_auto_20171111_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logoanalyze',
            old_name='suggested_logo_name',
            new_name='logo_name_1',
        ),
        migrations.RenameField(
            model_name='logoanalyze',
            old_name='precision',
            new_name='precision_1',
        ),
        migrations.AddField(
            model_name='logoanalyze',
            name='logo_name_2',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='logoanalyze',
            name='logo_name_3',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='logoanalyze',
            name='precision_2',
            field=models.CharField(default='0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='logoanalyze',
            name='precision_3',
            field=models.CharField(default='0.0', max_length=20),
        ),
    ]
