# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0004_auto_20171112_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoanalyze',
            name='pop_logo_name_1',
        ),
        migrations.RemoveField(
            model_name='logoanalyze',
            name='pop_logo_name_2',
        ),
        migrations.RemoveField(
            model_name='logoanalyze',
            name='pop_logo_name_3',
        ),
        migrations.RemoveField(
            model_name='logoanalyze',
            name='pop_precision_1',
        ),
        migrations.RemoveField(
            model_name='logoanalyze',
            name='pop_precision_2',
        ),
        migrations.RemoveField(
            model_name='logoanalyze',
            name='pop_precision_3',
        ),
    ]
